# SITE CONFIGURATION
baseurl: ""
url: "https://harshitrathod.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Harshit Rathod
  avatar: assets/img/avatar_v1.png
  favicon: assets/img/avatar_v1.png
  gravatar: # Email MD5 hash
  description: "An Altruistic Coder" # used by search engines

  # Header and footer text
  header_text: >
     <h2>Hello Internet!!!</h2> I am <b>Harshit Rathod</b>, Ahmedabad based Full stack developer. This is my little digital world where I like to
     to put my programming thoughts.
  header_text_feature_image:
  footer_text: Harshit Rathod © 2017. All Rights Reserved.

  # Icons
  rss: false
  email_address: "harshitrathodddu@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "harshit.rathod.cool"
  flickr:
  gitlab:
  github: "harshitrathod"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/harshit-rathod-068894bb/"   # Full URL
  pinterest:
  reddit: "harshitrathod"
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "Harshit__Rathod"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "harshitrathod"
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
keep_files: [.git]
